name: dev

on: 
    push:
        branches: [dev]

jobs:
    lint:
        name: format & clippy
        runs-on: ubuntu-latest
        steps:
            - name: check os release
              run: cat /etc/os-release
            - uses: action/checkout@v4
            - uses: EmbarkStudios/cargo-deny-action@v2
              with:
                commmand: check advisories


