name: dev

on: 
    push:
        branches: [dev]

jobs:
    lint:
        name: format & clippy
        runs-on: ubuntu-latest
        steps:
            - name: check os release
              run: cat /etc/os-release
            - uses: actions/checkout@v4
            - uses: taiki-e/install-action@v2
              with:
                tool: cargo-deny
            - run: cargo deny check advisories


